### ISSUE TITLE
Auto run installers

### ISSUE THREAD

**Issue by Mte90** [Mte90/gitapper#5]
If the repo has composer or npm it should automatically execute the install after the clone

**Comment by Stronkness** [comment]
Hello! I think i can take this issue on for the Hacktoberfest 2022 if thats okay?

If yes, could you clarify here what you want with this issue? Specific files?

**Comment by Mte90** [comment]
Sure, so https://github.com/Mte90/gitapper/blob/master/hooks/post-clone.sh

It should include a code that check if the folder has `package.json`, `requirements.txt`, `composer.json` and execute their package manager like npm, pip, composer etc.

In this way when the tool is used to clone a repository after join the folder it will download the various dependencies required.

**Comment by Stronkness** [comment]
Thank you for the clarification. If you like, you can assign it to me and i could take a look at it during October

**Comment by Mte90** [comment]
Perfect the task is yours :-)

**Comment by Stronkness** [comment]
Could you do me as an Assigne?

**Comment by Mte90** [comment]
To assign it to you I have to add you as collaborator on the project, based on the previous hacktoberfest experiences I don't do that anymore before to see a real contribution to my repositories as people usually disappear after adding them...

**Comment by Stronkness** [comment]
I understand. Thank you for clarifying

**Comment by Stronkness** [comment]
Do we assume they have for example pip, npm and composer installera?

**Comment by Mte90** [comment]
Well the script should check if the folder has the file with the packages and the package manager or gitapper would crash if doesn't find the command...

**Comment by Stronkness** [comment]
Perfect, then i must ask. Is this for Linux only? Because on Windows its a whole other story of implementing this script

(Also i will take a look at this issue this week)

**Comment by Mte90** [comment]
I am using it only on Linux so I don't know for Windows about bash/WSL so I think that you can focus just on linux.

**Comment by Stronkness** [comment]
I have uploaded a PR now. I know it looks horrible codewise. Please give input in the PR if something feels off
