### ISSUE TITLE
Verify code style

### ISSUE THREAD

**Issue by Mte90** [Mte90/gitapper#8]
The project is built with bash and python for Linux.

So this means check the code with shellcheck and pylint and add the files for use those tools in the project (and mention it in the readme).

**Comment by Stronkness** [comment]
The purpose is to check all code with shellcheck and pylint and ass the changes to the files?
Also mention it in the readme?

**Comment by Mte90** [comment]
Yes :-D

**Comment by Stronkness** [comment]
I can take a look at it then!

**Comment by Mte90** [comment]
The floor is yours :-D

Also if you find a better way to explain the project in the readme is very appreciated :-D

**Comment by Stronkness** [comment]
Hi. Im soon done with this issue. In pre-fork.sh these are not used. Am I supposed to have "export" before them or just comment them out?

```bash
        protocol=${BASH_REMATCH[1]}
        separator=${BASH_REMATCH[2]}
        hostname=${BASH_REMATCH[3]}
```

**Comment by Mte90** [comment]
I think that can be removed without issues.
