### ISSUE TITLE
Add video screenshot in readme

### ISSUE THREAD

**Issue by Mte90** [Mte90/gitapper#9]
Add a video on asciicinema or a gif of the tool in execution with some commands like `git fork` in the readme.

The tool is for linux, in case someone forgot it.

**Comment by Stronkness** [comment]
Im having issues with this. When i do the Installation in README and do for example "git fork" it just says that fork is not a command. What is the solution to this?

**Comment by Mte90** [comment]
Did you add the alias as written in the readme?

Gitapper is a tool that run git, is like a wrapper so you need to change for that `git` command your machine is looking for.

**Comment by Stronkness** [comment]
Yes i added the alias in .bashrc

**Comment by Mte90** [comment]
But you are using bash otherwise that change doesn't make sense as it is a configuration file for that terminal client.

**Comment by Stronkness** [comment]
That was what i thought about too. Its quite weird that it doesnt work for me

**Comment by Mte90** [comment]
Maybe you need to open a new bash client or doesn't find the change?

**Comment by Stronkness** [comment]
![image](https://user-images.githubusercontent.com/50335484/194035099-57b03450-e059-47dc-ad4c-9705a1fa0c14.png)

Restarted the computer also

**Comment by Mte90** [comment]
If you execute `echo "$SHELL"` on your terminal there is written bash?

**Comment by Stronkness** [comment]
That might be the problem, i have fish installed. I will try with changing to bash later, thanks!

**Comment by Mte90** [comment]
Thanks for your showcase, I did another one that to me is more clear about the difference.

**Comment by Stronkness** [comment]
My linux machine works again and now when i did the `git fork` it gave out different outputs than on my previous one, Now i understand what you mean that it gave the wrong outputs in my gif. Thank you

**Comment by Mte90** [comment]
No problem, it is also `me` that often doesn't explains pretty well what I am trying to say 😅
